name: Lint

on:
  push:
    paths:
      - "**/*.py"
  pull_request:
    paths:
      - "**/*.py"
  workflow_dispatch: # for test

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true


jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.5

      - name: pip update
        run: |
          pip install --upgrade pip

      - name: Install flit
        run: | 
          pip install flit~=3.7.1

      - name: Install Python dependencies
        run: | 
          pip install .

      - name: Install Python lint dependencies
        run: |
          pip install .[lint]

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          black: true
          flake8: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
